name: Build Visual Studio Project
 
on: [push]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: '16.0'
        components: 'Microsoft.VisualStudio.Workload.NativeDesktop,Microsoft.VisualStudio.Workload.ManagedDesktop'
 
    - name: Build the project
      run: msbuild /restore EDR-Preloader.vcxproj
